package com.social.wakesync.feature.games

import androidx.compose.animation.core.animateDpAsState
import androidx.compose.animation.core.spring
import androidx.compose.animation.core.tween
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsPressedAsState
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.key
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.scale
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.hapticfeedback.HapticFeedbackType
import androidx.compose.ui.platform.LocalHapticFeedback
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.social.wakesync.ui.theme.AppColorPalette
import kotlinx.coroutines.delay
import kotlin.math.abs
import kotlin.random.Random

private const val SIDE = 4
private const val TILE_COUNT = SIDE * SIDE // 16 (15 tiles + blank)
private const val BLANK = 0
private const val SHUFFLE_MOVES = 140 // random legal moves from solved — always solvable
private const val WIN_DELAY_MS = 450L

/**
 * Sliding Tiles — a classic 4×4 fifteen-puzzle wake-up challenge.
 *
 * Solvability is structural: the board is generated by performing
 * [SHUFFLE_MOVES] random *legal* moves from the solved state, so the puzzle is
 * guaranteed reachable (never an impossible permutation, never starting solved).
 *
 * Tap a tile adjacent to the blank to slide it (animated). Tiles in their
 * correct position get a subtle green edge + a ✓ marker; movable tiles get a
 * subtle cyan edge — but color is never the only cue (markers/borders/numbers).
 * Solved detection is exact: 1..15 in order with the blank last.
 *
 * Fully self-contained: no alarm logic, no network, no resources.
 */
@Composable
fun SlidingTilesGame(
    onGameCompleted: () -> Unit,
    onGameFailed: (() -> Unit)? = null,
    titleFamily: FontFamily = FontFamily.Default,
    interFamily: FontFamily = FontFamily.Default
) {
    // ── Game state ────────────────────────────────────────────────────────────
    var board by remember { mutableStateOf(generateSolvableBoard()) }
    var moves by remember { mutableIntStateOf(0) }
    var isComplete by remember { mutableStateOf(false) }
    var puzzleVersion by remember { mutableIntStateOf(0) } // bumps regenerate the board
    var lastRejected by remember { mutableIntStateOf(-1) } // subtle feedback on illegal tap
    var elapsedSeconds by remember { mutableIntStateOf(0) }
    // Reset per board version.
    LaunchedEffect(puzzleVersion) {
        board = generateSolvableBoard()
        moves = 0
        elapsedSeconds = 0
        isComplete = false
        lastRejected = -1
    }

    // Completion timer (stops counting on solve — cancelled automatically).
    LaunchedEffect(puzzleVersion, isComplete) {
        while (!isComplete) {
            delay(1000)
            if (!isComplete) elapsedSeconds++
        }
    }

    val haptic = LocalHapticFeedback.current

    fun onTileTapped(tileValue: Int) {
        if (isComplete) return
        val idx = board.indexOf(tileValue)
        val blankIdx = board.indexOf(BLANK)
        if (idx == -1 || !isAdjacent(idx, blankIdx)) {
            // Illegal tap: subtle feedback, board unchanged.
            lastRejected = tileValue
            return
        }
        GameSounds.tick()
        lastRejected = -1
        board = board.toMutableList().apply {
            this[idx] = BLANK
            this[blankIdx] = tileValue
        }
        moves++
        if (isSolved(board)) {
            isComplete = true
            GameCombo.reset()
            GameSounds.spark()
            haptic.performHapticFeedback(HapticFeedbackType.LongPress)
            onGameCompleted()
        }
    }

    // Rejected-tap feedback decay.
    LaunchedEffect(lastRejected) {
        if (lastRejected != -1) {
            delay(350)
            lastRejected = -1
        }
    }

    val correctCount = board.withIndex().count { (i, v) -> v != BLANK && v == i + 1 }
    val progress = correctCount.toFloat() / (TILE_COUNT - 1)

    // ── UI ───────────────────────────────────────────────────────────────────
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        // Header
        Text(
            text = "Sliding Tiles",
            color = Color.White,
            fontSize = 26.sp,
            fontWeight = FontWeight.W900,
            fontFamily = titleFamily,
            textAlign = TextAlign.Center
        )
        Text(
            text = "Arrange the numbers from 1 to 15.",
            color = Color.White.copy(alpha = 0.55f),
            fontSize = 13.sp,
            fontWeight = FontWeight.Bold,
            fontFamily = interFamily,
            textAlign = TextAlign.Center
        )

        if (!isComplete) {
            PhaseBanner(
                phase = GamePhase.ACT,
                text = when {
                    moves == 0 -> "✋ Slide tiles into the empty space"
                    correctCount >= TILE_COUNT - 3 -> "🔥 Almost there — $correctCount / 15 placed!"
                    else -> "✋ Keep sliding — $correctCount / 15 placed"
                },
                interFamily = interFamily
            )

            // Stats row
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.Center,
                verticalAlignment = Alignment.CenterVertically
            ) {
                StepCounter(
                    text = "Moves: $moves   ·   ⏱ ${elapsedSeconds}s",
                    phase = GamePhase.INFO,
                    titleFamily = titleFamily
                )
            }

            // Progress bar
            Box(
                Modifier
                    .fillMaxWidth(0.8f)
                    .height(5.dp)
                    .clip(RoundedCornerShape(99.dp))
                    .background(Color.White.copy(alpha = 0.1f))
            ) {
                Box(
                    Modifier
                        .fillMaxWidth(progress)
                        .height(5.dp)
                        .clip(RoundedCornerShape(99.dp))
                        .background(AppColorPalette.WinGreen)
                )
            }

            // ── Board: absolute-positioned animated tiles ─────────────────────
            BoxWithConstraints(
                modifier = Modifier
                    .fillMaxWidth()
                    .aspectRatio(1f)
            ) {
                val boardWidth = maxWidth
                val cell = boardWidth / SIDE
                key(puzzleVersion) {
                    board.forEachIndexed { idx, value ->
                        if (value != BLANK) {
                            SlidingTile(
                                value = value,
                                index = idx,
                                cellSize = cell,
                                isCorrect = value == idx + 1,
                                isMovable = isAdjacent(idx, board.indexOf(BLANK)),
                                isRejected = lastRejected == value,
                                onClick = { onTileTapped(value) },
                                titleFamily = titleFamily
                            )
                        }
                    }
                }
            }

            // First-visit coaching
            if (moves == 0) {
                HowToHint(
                    text = "How to play: tap a tile next to the empty space to slide it. Build 1 → 15!",
                    interFamily = interFamily
                )
            }
        } else {
            // Victory panel
            Spacer(modifier = Modifier.height(8.dp))
            Text("🎉", fontSize = 64.sp)
            Text(
                text = "Puzzle Complete!",
                color = AppColorPalette.WinGreen,
                fontSize = 30.sp,
                fontWeight = FontWeight.W900,
                fontFamily = titleFamily,
                textAlign = TextAlign.Center
            )
            Text(
                text = "Solved in $moves moves · ${elapsedSeconds}s 🧱",
                color = Color.White.copy(alpha = 0.6f),
                fontSize = 13.sp,
                fontWeight = FontWeight.Bold,
                fontFamily = interFamily,
                textAlign = TextAlign.Center
            )
        }
    }
}

/**
 * A single animated tile. Position is derived from its board index via Dp
 * offsets animated with a spring — tiles glide smoothly into the blank.
 */
@Composable
private fun SlidingTile(
    value: Int,
    index: Int,
    cellSize: Dp,
    isCorrect: Boolean,
    isMovable: Boolean,
    isRejected: Boolean,
    onClick: () -> Unit,
    titleFamily: FontFamily
) {
    val haptic = LocalHapticFeedback.current
    val iSource = remember { MutableInteractionSource() }
    val pressed by iSource.collectIsPressedAsState()

    val row = index / SIDE
    val col = index % SIDE

    // Cell size = parent fraction; offset per row/col. Board is square with
    // 10dp gaps absorbed into the padding math below (2dp padding per side
    // keeps numbers crisp at any size).
    val targetX = cellSize * col
    val targetY = cellSize * row

    val animX by animateDpAsState(targetX, spring(dampingRatio = 0.75f, stiffness = 500f), label = "tileX$value")
    val animY by animateDpAsState(targetY, spring(dampingRatio = 0.75f, stiffness = 500f), label = "tileY$value")

    val targetScale = when {
        isRejected -> 0.9f
        pressed -> 0.94f
        else -> 1f
    }
    val scale by androidx.compose.animation.core.animateFloatAsState(
        targetValue = targetScale,
        animationSpec = spring(dampingRatio = 0.5f, stiffness = 700f),
        label = "tileScale$value"
    )

    val accent = if (isCorrect) AppColorPalette.WinGreen else AppColorPalette.CyanCta

    Box(
        modifier = Modifier
            .offset(x = animX, y = animY)
            .size(cellSize)
            .padding(3.dp)
            .scale(scale)
            .shadow(if (pressed) 2.dp else 6.dp, RoundedCornerShape(18.dp))
            .clip(RoundedCornerShape(18.dp))
            .background(
                if (isCorrect) AppColorPalette.WinGreen.copy(alpha = 0.22f)
                else AppColorPalette.Surface
            )
            .border(
                width = if (isMovable || isCorrect) 2.dp else 1.2.dp,
                color = accent.copy(alpha = if (isCorrect || isMovable) 0.8f else 0.35f),
                shape = RoundedCornerShape(18.dp)
            )
            .clickable(
                interactionSource = iSource,
                indication = null
            ) {
                if (isMovable) {
                    haptic.performHapticFeedback(HapticFeedbackType.TextHandleMove)
                    onClick()
                }
                // Non-movable taps are ignored by design (spec) — no crash, no move.
            },
        contentAlignment = Alignment.Center
    ) {
        Column(horizontalAlignment = Alignment.CenterHorizontally) {
            Text(
                text = value.toString(),
                color = if (isCorrect) AppColorPalette.WinGreen else Color.White,
                fontSize = if (value >= 10) 24.sp else 27.sp,
                fontWeight = FontWeight.W900,
                fontFamily = titleFamily
            )
            // Non-color cue for "correctly placed": a small check marker.
            if (isCorrect) {
                Text(
                    text = "✓",
                    color = AppColorPalette.WinGreen,
                    fontSize = 10.sp,
                    fontWeight = FontWeight.Black
                )
            }
        }
    }
}

// ── Board logic (pure functions — testable, no Compose deps) ────────────────

/** True when [a] and [b] are orthogonally adjacent on the 4×4 board. */
internal fun isAdjacent(a: Int, b: Int): Boolean {
    val ra = a / SIDE
    val ca = a % SIDE
    val rb = b / SIDE
    val cb = b % SIDE
    return (ra == rb && abs(ca - cb) == 1) || (ca == cb && abs(ra - rb) == 1)
}

/** Exact solved check: 1..15 in order, blank (0) last. */
private fun isSolved(board: List<Int>): Boolean =
    board.withIndex().all { (i, v) -> if (i == TILE_COUNT - 1) v == BLANK else v == i + 1 }

/**
 * Generates a guaranteed-solvable board: performs [SHUFFLE_MOVES] random legal
 * moves from the solved state. Reachability is structural. The result is also
 * guaranteed not to already be solved.
 */
internal fun generateSolvableBoard(): List<Int> {
    var board = (1..15).toList() + listOf(BLANK)
    var blankIdx = TILE_COUNT - 1
    var previousIdx = -1

    repeat(SHUFFLE_MOVES) {
        val neighbors = (0 until TILE_COUNT).filter { isAdjacent(it, blankIdx) && it != previousIdx }
        val next = neighbors.random(Random)
        board = board.toMutableList().apply {
            this[blankIdx] = this[next]
            this[next] = BLANK
        }
        previousIdx = blankIdx
        blankIdx = next
    }

    // Extremely unlikely after 140 moves, but never ship a pre-solved board.
    if (isSolved(board)) return generateSolvableBoard()
    return board
}

/**
 * Adapter used by GameRouter (practice demo + real alarm ladder).
 * [round] re-seeds the whole game — a new practice round or ladder stage
 * generates a fresh solvable board. Victory maps to [onSuccess].
 */
@Composable
fun SlidingTilesGame(
    round: Int,
    onSuccess: () -> Unit,
    titleFamily: FontFamily,
    interFamily: FontFamily
) {
    key(round) {
        SlidingTilesGame(
            onGameCompleted = onSuccess,
            titleFamily = titleFamily,
            interFamily = interFamily
        )
    }
}
